### ISSUE TITLE
Datavalidering vid skapat ärende finns inte

### ISSUE THREAD

**Issue by henninghall** [Rovanion/AinAppen#20]
Tex ska det kontrolleras att:
- Obligatorisk information är inskriven (brottsrubricering, befälhavar-id ... )
- Befälhavar-ID inte är för långt (appen krachar vid för stort integer-värde)

**Comment by henninghall** [comment]
Har fortfarande problem med detta, plz help.

**Comment by Rovanion** [comment]
Hmm, någon borde definitivt titta på det här. Jag ska se om någon av våra seniora ärendehanterare kan ta en titt på ärendet.
