### ISSUE TITLE
Appen hänger sig när skärmen roteras

### ISSUE THREAD

**Issue by samuelnilsson** [Rovanion/AinAppen#23]
Appen hänger sig när skärmen roteras i de flesta low-level fragments.

**Comment by Rovanion** [comment]
Vore gött om någon kan bena ut vilka så vet vi definitivt när vi kan stänga
den här felrapporten.

Den 3 april 2014 21:03 skrev samni698 notifications@github.com:

**Comment by samuelnilsson** [comment]
Detta sker då dessa är öppna och skärmen roteras:
CaseFragment och i EditCaseFragment (som inte ligger i master men i min pull request)
