### ISSUE TITLE
Bakåtpilen försvinner när skärm roteras

### ISSUE THREAD

**Issue by samuelnilsson** [Rovanion/AinAppen#24]
Bakåtknappen uppe i det vänstra hörnet försvinner i bland annat skapa ärende-läget när skärmen roteras.

**Comment by Rovanion** [comment]
Så det sker inte varje gång skärmen roteras?

Den 3 april 2014 21:04 skrev samni698 notifications@github.com:

**Comment by samuelnilsson** [comment]
Detta sker i AddCaseFragment men det är möjligt att det även sker i de fragment som krachar när skärmen roteras (alltså de fragment i issue #23 ), förutsatt att det inte krachar. Just nu är nämligen AddCaseFragment det enda fragment som har en bakåtpil och inte krachar då skärmen roteras.

**Comment by Rovanion** [comment]
:D

Den 4 april 2014 08:57 skrev samni698 notifications@github.com:
